### ISSUE TITLE
Where did old issue go?

### ISSUE THREAD

**Issue by jihoonl** [yujinrobot/navigation#2]
I remember one or two issues kept open here. 

Did anybody remove the repo and refork?

**Comment by jihoonl** [comment]
Also Jorge's concert patch was gone in the source too..........

**Comment by corot** [comment]
maybe you don't need it anymore.... you will notice as soon as you run a concert with a shared map for all the agents

**Comment by jihoonl** [comment]
Eh.. really? It caused a problem last week demo...what patch fixed the problem?

**Comment by corot** [comment]
Which problem?  A big delay when clearing the global costmap? It should be something like "add a first_map_only parameter"
What it does is to store the first map the robot receives so it doesn't need to get it again through the network with any call to clear map service.

**Comment by jihoonl** [comment]
Yeah.  [first_map_only](https://github.com/yujinrobot/navigation/commit/e4eb8aa0523a5ae43b689ab8c3f57bf43020a8f1) patch is not necessary anymore for concert?

**Comment by corot** [comment]
몰라... that's what I said, that maybe it's not needed anymore. But as you mentioned a problem you experienced on last demo....  maybe is the same one!

**Comment by jihoonl** [comment]
넹. This patch is essential to run waiterbot until we bring in  world canvas :kissing_heart:

**Comment by stonier** [comment]
Marcus moved it to [graveyard_navigation](https://github.com/yujinrobot/graveyard_navigation) so the latest navigation stack could be brought in. Looks like he was so busy he forgot to update you on this. You can either use that one, or cherry-pick across that commit to this one.

From both of us...big apologies for not giving you the heads up!

**Comment by bit-pirate** [comment]
Hm, doesn't look like the issues have been moved as well ... >.<

Sorry!

**Comment by jihoonl** [comment]
Ah. ok. I just wanted to know where it has gone. closing the issue.
