### ISSUE TITLE
cleanup branches.

### ISSUE THREAD

**Issue by jihoonl** [yujinrobot/navigation#3]
too many branches from upstream. cleaning up.

leaving only indigo-devel : there is no devel in upstream. They maintain both indigo and hydro with hydro-devel branch which confused me.

**Comment by bit-pirate** [comment]
:+1:

**Comment by bit-pirate** [comment]
When done, then I'll change https://github.com/yujinrobot/yujin_tools/blob/master/rosinstalls/indigo/yujin_navigation.rosinstall

**Comment by jihoonl** [comment]
Done. Now it has only `indigo-devel` branch.
